services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: partner-bff-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: partner-transaction-bff
    ports:
      - "5080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      PartnerVerification__BaseUrl: http://localhost:8080
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__User: guest
      RabbitMq__Password: guest
      RabbitMq__QueueName: partner-transactions
      Security__RequireApiKey: "true"
      Security__ApiKey: dev-assessment-key
    depends_on:
      rabbitmq:
        condition: service_healthy
